### ISSUE TITLE
Shooting players is borked

### ISSUE THREAD

**Issue by whizzer0** [neontribe/untangled-2017#139]
```
Traceback (most recent call last):
  File "./client.py", line 417, in <module>
    g.run()
  File "./client.py", line 397, in run
    hit_me = spell.hit_target_player(me)
  File "/home/pi/code/untangled-2017/player.py", line 444, in hit_target_player
    return player.rect.colliderect(self.rect)
TypeError: Argument must be rect style object
```

**Comment by whizzer0** [comment]
Presumably fixed
