### ISSUE TITLE
Crash when trying to shoot with no mana

### ISSUE THREAD

**Issue by whizzer0** [neontribe/untangled-2017#93]
Happened while moving and pressing R to shoot.

```Traceback (most recent call last):
  File "./client.py", line 370, in <module>
    g.run()
  File "./client.py", line 342, in run
    self.network.node.shout("world:combat", bson.dumps(me.cast_spells[-1].get_properties()._asdict()))
IndexError: list index out of range

**Comment by Spannner** [comment]
Fixed in pull request #100
